import { EmptyState } from "../../components/common/EmptyState.jsx";
import { ensureArray, ensureObject } from "../../utils/arrays.js";
import { formatTimestamp } from "../../utils/formatters.js";

export function DailyBriefPanel({ brief, loading, onGenerate }) {
  const payload = ensureObject(brief);
  const text = payload.report_text || "";
  const sections = String(text).split(/\n\n+/).filter(Boolean);
  const tickers = ensureArray(payload.raw?.tickers);

  return (
    <section className="panel wide" id="daily-brief">
      <div className="panel-heading">
        <div>
          <p className="eyebrow">Auto-generated by the cache agent</p>
          <h2>Latest Daily Brief</h2>
        </div>
        <button onClick={onGenerate} disabled={loading}>
          {loading ? "Generating..." : "Generate Brief Now"}
        </button>
      </div>

      {!text ? (
        <EmptyState title="No brief saved yet">
          The Auto Cached Agent writes a watchlist brief on each scheduled run. Click Generate Brief
          Now to create and persist one immediately.
        </EmptyState>
      ) : (
        <>
          <p className="muted small">
            Saved {formatTimestamp(payload.created_at)} | {payload.report_date || "unknown date"} |{" "}
            {tickers.length || 0} tickers
          </p>
          <div className="report-sections">
            {sections.map((section, index) => (
              <article className="report-section" key={index}>
                <pre>{section}</pre>
              </article>
            ))}
          </div>
        </>
      )}
    </section>
  );
}
