// Per-class teaching contexts, part B: deep learning, optimization,
// big data/Spark, experimentation/causal inference, and GenAI.
import { pool } from './sources.mjs';

export const CONTEXTS_B = {
  'Neural Networks': {
    domain: 'neural networks',
    overview: 'A neural network composes layers of weighted sums passed through nonlinear activation functions (sigmoid, ReLU); training minimizes a loss function by gradient descent, with gradients computed efficiently by backpropagation.',
    why: 'Neural networks power modern AI; understanding layers, activations, loss, and backprop is the entry ticket to deep learning, CNNs, RNNs, and transformers.',
    workplace: 'Analysts fit small feed-forward networks on tabular problems and, more often, consume pretrained deep models — both require reading architecture and training diagnostics.',
    scenario: 'Your network predicts the same value for every input; checking reveals unscaled features saturating the sigmoid activations — preprocessing, not architecture, was the bug.',
    mistakes: ['Feeding unscaled inputs, which cripples gradient-based training.', 'Training until training loss stops falling instead of stopping on validation loss.'],
    sources: pool('goodfellow', 'rumelhart', 'cs229', 'geron', 'bishop'),
  },
  'Gradients and Regularization': {
    domain: 'optimization of neural networks',
    overview: 'Training is numerical optimization: gradient descent and stochastic variants (SGD, momentum, Adam) follow the negative gradient with a learning rate; regularization (L1/L2 weight penalties, dropout, early stopping) fights overfitting by constraining capacity.',
    why: 'Learning rate and regularization settings decide whether a network converges, diverges, or memorizes; these are the dials you actually turn in practice.',
    workplace: 'Model tuning sessions are largely learning-rate schedules, batch sizes, and dropout/weight-decay choices read off training-vs-validation curves.',
    scenario: 'Training loss falls while validation loss climbs after epoch 12 — classic overfitting; early stopping and dropout close the gap.',
    mistakes: ['Setting the learning rate too high (divergence) or too low (no progress) without inspecting loss curves.', 'Applying dropout at inference time instead of training only.'],
    sources: pool('goodfellow', 'cs231n', 'esl', 'geron', 'pytorchDocs'),
  },
  'Classification Deep Dive': {
    domain: 'deep classification',
    overview: 'Deep classifiers end in a softmax layer producing class probabilities trained with cross-entropy loss; practical skill includes encoding targets, handling class imbalance, calibration, and reading per-class metrics.',
    why: 'Most applied deep learning is classification; the softmax/cross-entropy pattern recurs in vision, text, and tabular models alike.',
    workplace: 'Document-routing and image-QC systems are softmax classifiers whose thresholds and per-class errors you must tune to business costs.',
    scenario: 'A 10-class product classifier hits 90% overall but 30% on the rarest class that matters most; class weights and resampling fix the imbalance.',
    mistakes: ['Using accuracy with imbalanced classes instead of per-class recall/precision.', 'Interpreting softmax outputs as calibrated probabilities without checking calibration.'],
    sources: pool('goodfellow', 'cs231n', 'sklearn', 'geron', 'bishop'),
  },
  'Feed-Forward Architecture': {
    domain: 'feed-forward networks',
    overview: 'Feed-forward (dense/MLP) architecture stacks fully connected layers; design choices are depth, width, activation functions, and output layer matching the task — plus parameter counting (weights = inputs×units, biases = units).',
    why: 'The MLP is the template all other architectures modify; being able to count parameters and reason about capacity prevents both underfitting and memory blowups.',
    workplace: 'Tabular deep models and the dense "heads" on top of CNNs/transformers are feed-forward blocks you will size and regularize.',
    scenario: 'You must justify a model to IT: counting parameters (e.g., 8 inputs × 16 units + 16 biases) shows exactly the memory and compute footprint.',
    mistakes: ['Adding layers when more data or better features were the real constraint.', 'Forgetting bias terms when counting parameters.'],
    sources: pool('goodfellow', 'cs231n', 'bishop', 'geron', 'pytorchDocs'),
  },
  'Support Vector Machines': {
    domain: 'SVMs',
    overview: 'SVMs find the maximum-margin hyperplane separating classes; soft margins (cost parameter C) tolerate violations, and kernels (polynomial, RBF) implicitly map data into higher dimensions where linear separation works.',
    why: 'SVMs formalize the margin/regularization idea that pervades ML and remain strong on medium-sized, high-dimensional data such as text.',
    workplace: 'Text classification and quality-control problems with thousands of features are classic SVM territory, tuned over C and kernel width.',
    scenario: 'Spam data is not linearly separable in raw features; an RBF kernel separates it cleanly without manual feature crosses.',
    mistakes: ['Skipping feature scaling, which distorts margin geometry.', 'Grid-searching kernels without nested validation, overfitting the tuning set.'],
    sources: pool('cortes', 'islr', 'esl', 'bishop', 'sklearn'),
  },
  'AutoEncoders': {
    domain: 'autoencoders',
    overview: 'An autoencoder learns to reconstruct its input through a low-dimensional bottleneck: encoder compresses, decoder reconstructs, and reconstruction error trains both — yielding nonlinear dimension reduction, denoising, and anomaly detection.',
    why: 'Autoencoders are the deep-learning answer to PCA and the standard unsupervised tool for anomaly detection in operations and fraud.',
    workplace: 'Manufacturing and fraud teams flag anomalies as records the autoencoder reconstructs poorly — no labels required.',
    scenario: 'With almost no labeled fraud, you train an autoencoder on normal transactions; the top reconstruction-error cases become the investigation queue.',
    mistakes: ['Making the bottleneck so wide the network learns the identity function.', 'Using reconstruction error thresholds without validating against known anomalies.'],
    sources: pool('goodfellow', 'geron', 'cs231n', 'sklearn', 'bishop'),
  },
  'Convolutional Neural Networks (CNNs)': {
    domain: 'CNNs',
    overview: 'CNNs exploit spatial structure: convolutional filters slide across the input detecting local patterns, pooling layers downsample, and stacked layers compose edges into textures into objects — with weight sharing keeping parameters manageable.',
    why: 'CNNs made computer vision practical and their ideas (local receptive fields, weight sharing, hierarchy) echo across modern architectures.',
    workplace: 'Defect detection, document OCR, and shelf-image analytics are CNN applications analysts increasingly fine-tune rather than build from scratch.',
    scenario: 'A receipt-processing pipeline fine-tunes a pretrained CNN to classify document types, reaching production accuracy with only 2,000 labeled images.',
    mistakes: ['Flattening images into dense layers, discarding spatial structure.', 'Training from scratch when transfer learning from pretrained weights is faster and better.'],
    sources: pool('lecun', 'cs231n', 'goodfellow', 'geron', 'pytorchDocs'),
  },
  'Recurrent Neural Networks (RNNs)': {
    domain: 'RNNs',
    overview: 'RNNs process sequences by carrying a hidden state across time steps; vanilla RNNs suffer vanishing gradients, which LSTM and GRU gating solve — historically powering language and time-series models before transformers.',
    why: 'Sequence thinking (state, order, memory) underlies forecasting and NLP; LSTMs still serve time-series work, and RNN limitations motivate attention/transformers.',
    workplace: 'Demand forecasting and sensor-stream models still use LSTM/GRU layers where data is modest and latency matters.',
    scenario: 'A sales forecast needs last quarter’s pattern, not just last week’s; an LSTM’s gated memory captures the longer dependency a vanilla RNN loses.',
    mistakes: ['Ignoring vanishing/exploding gradients on long sequences.', 'Shuffling time-series rows during training, destroying temporal order.'],
    sources: pool('hochreiter', 'goodfellow', 'cs224n', 'geron', 'tfDocs'),
  },
  'Ensemble-Hybrid Learning': {
    domain: 'ensemble learning',
    overview: 'Ensemble learning combines diverse models — bagging for variance reduction, boosting for bias reduction, stacking with a meta-learner, and hybrid pipelines mixing model families — because uncorrelated errors cancel.',
    why: 'Ensembles win most tabular benchmarks and competitions; knowing when and how to combine models is a high-leverage practical skill.',
    workplace: 'Production scoring systems often blend a gradient-boosted model with a neural model, stacked by a simple logistic meta-learner.',
    scenario: 'Three individually mediocre models with uncorrelated errors, averaged, beat your best single model on holdout — diversity did the work.',
    mistakes: ['Ensembling highly correlated models and expecting gains.', 'Training the stacking meta-learner on the same data the base models saw (leakage).'],
    sources: pool('esl', 'breiman', 'islr', 'sklearn', 'geron'),
  },

  'Introduction & Overview to Modeling and Optimization': {
    domain: 'prescriptive analytics',
    overview: 'Prescriptive analytics recommends actions: an optimization model encodes decisions as variables, the goal as an objective function, and business rules as constraints, then a solver finds the best feasible decision.',
    why: 'Prediction tells you what will happen; optimization tells you what to do about it — the highest rung of the analytics value ladder.',
    workplace: 'Production planning, staffing, pricing, and logistics all run on optimization models maintained by analytics teams.',
    scenario: 'Given a demand forecast, leadership still must decide production quantities under capacity limits — an optimization model, not another forecast, answers that.',
    mistakes: ['Jumping to a solver before writing down decisions, objective, and constraints in words.', 'Treating model output as a mandate rather than a decision-support input.'],
    sources: pool('hillier', 'winston', 'mitocwOpt', 'amplBook', 'boyd'),
  },
  'Introduction into Mathematical Programming': {
    domain: 'mathematical programming',
    overview: 'Mathematical programming formalizes optimization: decision variables, a linear or nonlinear objective, and equality/inequality constraints define a feasible region searched by algorithms; LP, IP, and NLP differ by variable and function types.',
    why: 'The formulation discipline — translating a messy business problem into variables, objective, constraints — is the transferable skill; solvers handle the rest.',
    workplace: 'Analysts write formulations in Excel Solver, Python (PuLP/Pyomo), or AMPL, then defend the model’s assumptions to operations.',
    scenario: 'A blending problem in words becomes: minimize cost subject to nutrition constraints — once formulated, the solver answers in milliseconds.',
    mistakes: ['Confusing parameters (given data) with decision variables (what you control).', 'Forgetting non-negativity or integrality requirements implicit in the business.'],
    sources: pool('hillier', 'winston', 'amplBook', 'mitocwOpt', 'boyd'),
  },
  'Complexity and Algorithm Analysis': {
    domain: 'algorithm analysis',
    overview: 'Algorithm analysis measures cost growth with input size using Big-O notation: constant, logarithmic, linear, n log n, polynomial, and exponential classes; P vs NP separates problems solvable efficiently from those (like many integer programs) believed not to be.',
    why: 'Complexity explains why some analytics jobs finish in seconds and others never finish — and why heuristics exist for routing and scheduling problems.',
    workplace: 'Choosing between an exact optimizer and a heuristic for a 5,000-stop routing problem is a complexity judgment call.',
    scenario: 'A nested-loop deduplication script is O(n²); at 1M rows it would run for days, while a hash-based O(n) approach finishes in seconds.',
    mistakes: ['Reading Big-O as exact runtime instead of growth rate.', 'Assuming faster hardware fixes exponential algorithms — it cannot.'],
    sources: pool('clrs', 'hillier', 'mitocwOpt', 'winston', 'boyd'),
  },
  'Linear Programming (LP)': {
    domain: 'linear programming',
    overview: 'LP optimizes a linear objective over linear constraints with continuous variables; the feasible region is a polyhedron, optima occur at corner points, the simplex method walks them, and duality/sensitivity analysis prices each constraint via shadow prices.',
    why: 'LP is the workhorse of prescriptive analytics — fast, scalable, and rich in economic interpretation through shadow prices and reduced costs.',
    workplace: 'Product-mix, blending, scheduling, and transportation models are solved as LPs whose sensitivity reports drive "what if capacity grew?" conversations.',
    scenario: 'The sensitivity report shows a $42 shadow price on machine-hours; that single number justifies (or kills) the proposed overtime budget.',
    mistakes: ['Forcing inherently integer decisions into LP and rounding the answer.', 'Reading shadow prices outside their allowable range of validity.'],
    sources: pool('hillier', 'winston', 'amplBook', 'boyd', 'mitocwOpt'),
  },
  'Integer Programming (IP)': {
    domain: 'integer programming',
    overview: 'IP restricts variables to integers — including binary variables that encode yes/no decisions, fixed costs, and logical conditions (if-then, either-or); branch-and-bound solves IPs by exploring an LP-relaxation tree, at exponential worst-case cost.',
    why: 'Real decisions are lumpy: open a warehouse or not, assign a worker or not. Binary modeling tricks turn business logic into solvable mathematics.',
    workplace: 'Facility location, project selection, and crew scheduling are IPs; analysts spend their effort on tight formulations so branch-and-bound stays tractable.',
    scenario: 'Choosing at most 3 of 10 projects with dependencies ("B only if A") becomes binary constraints x_B ≤ x_A and Σx ≤ 3.',
    mistakes: ['Solving the LP relaxation and rounding, which can be infeasible or far from optimal.', 'Writing big-M constraints with needlessly huge M, weakening the relaxation.'],
    sources: pool('winston', 'hillier', 'amplBook', 'clrs', 'mitocwOpt'),
  },
  'Transportation and Assignment Problems': {
    domain: 'transportation problems',
    overview: 'Transportation problems ship from supply nodes to demand nodes at minimum cost; assignment problems match agents to tasks one-to-one. Both are special LPs with integral optimal solutions and very fast specialized algorithms.',
    why: 'These structures appear everywhere in operations — distribution, staffing, matching — and their integrality property means LP solves them exactly.',
    workplace: 'Distribution planners solve transportation models weekly to allocate plant output to regional warehouses at minimum freight cost.',
    scenario: 'Balancing three plants against five DCs with unequal supply and demand requires a dummy node — a standard modeling move.',
    mistakes: ['Forgetting to balance total supply and demand with a dummy source/sink.', 'Missing that the assignment problem is a transportation problem with all supplies and demands equal to one.'],
    sources: pool('hillier', 'winston', 'flowBook', 'mitocwOpt', 'amplBook'),
  },
  'Network Flow Problems': {
    domain: 'network flows',
    overview: 'Network flow models route flow through nodes and capacitated arcs: shortest path, maximum flow, and minimum-cost flow are the canonical problems, unified by flow-conservation constraints and blessed with integral solutions.',
    why: 'Supply chains, projects, and even matching problems reduce to network flows that solve at enormous scale.',
    workplace: 'Logistics teams compute min-cost flows over lane networks; project planners use longest paths (critical path method) on activity networks.',
    scenario: 'Max-flow analysis of a distribution network reveals the binding bottleneck arc — the one capacity expansion that actually increases throughput.',
    mistakes: ['Violating flow conservation when hand-building models.', 'Overlooking that many scheduling/matching problems are disguised network flows.'],
    sources: pool('flowBook', 'hillier', 'clrs', 'winston', 'mitocwOpt'),
  },

  'Big Data Systems': {
    domain: 'big data systems',
    overview: 'Big data systems distribute storage and compute across clusters: HDFS stores files in replicated blocks across data nodes; YARN allocates cluster resources; MapReduce processes data where it lives via map, shuffle/sort, and reduce phases; Hive and Sqoop bridge SQL and relational ingest; Spark supersedes MapReduce with in-memory execution.',
    why: 'The Hadoop-era architecture explains the why of every modern data platform — locality, replication, and shared-nothing parallelism still underpin Spark, Snowflake, and the cloud lakehouse.',
    workplace: 'Even on managed cloud platforms, you will reason about partitioning, shuffles, and data locality when jobs run slowly or cost too much.',
    scenario: 'A word-count over 1 TB of logs cannot move data to one machine; MapReduce moves the computation to the data blocks instead — the foundational big-data idea.',
    mistakes: ['Believing the name node stores data (it stores metadata only).', 'Forgetting that shuffle — moving data between map and reduce — is the expensive step.'],
    sources: pool('hadoopGuide', 'hadoopDocs', 'kleppmann', 'learningSpark', 'mmds'),
  },
  'Analytics on Big Data Platform - Apache Spark': {
    domain: 'Apache Spark',
    overview: 'Spark is a unified engine for large-scale data processing: resilient distributed datasets (RDDs) and DataFrames are partitioned across executors, transformations are lazy and only execute when an action triggers a job, and the Catalyst optimizer plans efficient execution.',
    why: 'Spark is the de facto standard for big-data analytics and the engine inside Databricks; lazy evaluation and partitioning explain both its speed and its surprises.',
    workplace: 'You will write PySpark DataFrame pipelines — filter, join, groupBy, aggregate — and read Spark UIs to debug slow stages.',
    scenario: 'Your "fast" pipeline does nothing for 20 minutes then everything at once: lazy evaluation deferred all work until the final write action.',
    mistakes: ['Calling collect() on a huge DataFrame and crashing the driver.', 'Ignoring partition counts, causing either tiny-task overhead or giant skewed tasks.'],
    sources: pool('sparkDocs', 'learningSpark', 'databricks', 'kleppmann', 'hadoopGuide'),
  },
  'Distributed Computing on Spark': {
    domain: 'Spark internals',
    overview: 'A Spark application has a driver coordinating executors; jobs split into stages at shuffle boundaries, stages into tasks (one per partition); wide transformations (joins, groupBy) shuffle data while narrow ones (map, filter) do not — and caching keeps hot data in memory.',
    why: 'Performance tuning is impossible without the driver/executor/stage/task mental model; it is the difference between guessing and engineering.',
    workplace: 'Reading the Spark UI to find skewed tasks, oversized shuffles, and missing caches is a routine on-call skill for data engineers.',
    scenario: 'One task in a 200-task stage runs 50× longer — data skew on a hot key; salting the key rebalances the stage.',
    mistakes: ['Confusing narrow and wide transformations when reasoning about shuffles.', 'Caching everything (memory pressure) or nothing (recomputation) instead of caching reused DataFrames.'],
    sources: pool('sparkDocs', 'learningSpark', 'kleppmann', 'databricks', 'hadoopDocs'),
  },
  'Machine Learning at Scale': {
    domain: 'distributed ML',
    overview: 'Spark MLlib scales ML via pipelines of transformers and estimators: feature stages (tokenizers, encoders, assemblers) feed estimators whose fit() produces models; cross-validation grids parallelize across the cluster; data parallelism trains on partitioned data.',
    why: 'When training data outgrows one machine, you need pipeline thinking and distributed tuning — the same API discipline scikit-learn teaches, at cluster scale.',
    workplace: 'Churn models on hundreds of millions of rows are trained as MLlib pipelines scheduled nightly on Databricks.',
    scenario: 'A grid search of 48 hyperparameter combinations finishes overnight because Spark evaluates folds in parallel across executors.',
    mistakes: ['Fitting preprocessing on the full dataset before splitting (leakage at scale).', 'Collecting features to the driver for "convenience", defeating distribution.'],
    sources: pool('sparkDocs', 'learningSpark', 'databricks', 'sklearn', 'esl'),
  },
  'Recommender Systems': {
    domain: 'recommender systems',
    overview: 'Recommenders predict preference: collaborative filtering uses user-item interaction patterns (user-based, item-based, matrix factorization/ALS), content-based methods use item attributes, and hybrids combine both — evaluated by ranking metrics and beset by cold-start and sparsity.',
    why: 'Recommendation drives revenue at retailers, streamers, and marketplaces; it is also the canonical large-scale ML system an analyst should understand end-to-end.',
    workplace: 'E-commerce teams run ALS matrix factorization on purchase histories, blending content features to handle new items.',
    scenario: 'A new product has no interaction history — cold start; content-based features carry it until collaborative signals accumulate.',
    mistakes: ['Evaluating recommendations by RMSE alone when top-k ranking is what users see.', 'Ignoring popularity bias, which buries niche items and feedback-loops the catalog.'],
    sources: pool('mmds', 'aggarwal', 'netflix', 'sparkDocs', 'esl'),
  },

  'Introduction to Business Experiments': {
    domain: 'business experimentation',
    overview: 'Business experiments compare treatments under controlled randomization to measure causal effects: define a research question, choose units and KPIs, randomize assignment, and read results with statistical care.',
    why: 'Correlation-driven decisions routinely fail; experiments are the gold standard for knowing what actually works before scaling it.',
    workplace: 'Product, marketing, and pricing teams gate launches behind experiments — the analyst designs, monitors, and adjudicates them.',
    scenario: 'A redesigned checkout "lifted" conversion in a before/after comparison, but seasonality explains it; only a randomized concurrent control isolates the design’s effect.',
    mistakes: ['Comparing before vs after instead of randomized concurrent groups.', 'Letting the team peek at results daily and stop when significance appears.'],
    sources: pool('kohavi', 'gerberGreen', 'montgomery', 'openintro', 'mixtape'),
  },
  'A/B Tesing': {
    domain: 'A/B testing',
    overview: 'A/B testing randomizes units between control and treatment to estimate the average treatment effect: formulate hypotheses, verify design assumptions (random sampling, random assignment), size the test with power analysis, run the appropriate test (t, proportion, randomization, or Bayesian beta-binomial), and report interval estimates.',
    why: 'A/B testing is the most-used causal tool in industry; its statistics — Type I/II errors, power, effect size, confidence and credible intervals — are core analyst literacy.',
    workplace: 'You will write the design checklist (question, treatment, unit, KPI, population, randomization, sample size), then defend conclusions to stakeholders with appropriate uncertainty language.',
    scenario: 'A 0.3pp conversion lift is observed; whether to ship depends on the confidence interval and the minimum effect that justifies engineering cost — not the point estimate alone.',
    mistakes: ['Running tests without a power calculation, then "finding nothing" because the test was undersized.', 'Slicing results across dozens of subgroups without multiple-testing control (FDR), then believing one significant slice.'],
    sources: pool('kohavi', 'openintro', 'gerberGreen', 'fdr', 'simpson'),
  },
  'A/B/n Testing': {
    domain: 'multi-variant testing',
    overview: 'A/B/n tests compare several treatments at once against control; analysis uses ANOVA-style global tests followed by pairwise comparisons with multiple-testing corrections, trading faster exploration against split traffic and power.',
    why: 'Real product questions rarely have one candidate; testing several variants correctly avoids both false winners and wasted traffic.',
    workplace: 'Marketing tests four subject lines simultaneously; the analysis must correct for six pairwise comparisons before crowning a winner.',
    scenario: 'With five variants, a naive 0.05 threshold per comparison inflates false-positive risk toward 40%; Bonferroni or FDR control restores honesty.',
    mistakes: ['Declaring the best-looking arm the winner without multiplicity correction.', 'Splitting traffic so many ways that no arm reaches adequate power.'],
    sources: pool('kohavi', 'montgomery', 'fdr', 'openintro', 'gerberGreen'),
  },
  'Blocking': {
    domain: 'blocked designs',
    overview: 'Blocking groups similar units (by region, store, customer segment) and randomizes within each block, removing block-to-block variation from the error term — "block what you can, randomize what you cannot."',
    why: 'Blocking buys power for free: the same sample detects smaller effects because nuisance variation is controlled by design rather than by luck.',
    workplace: 'Retail experiments block by store volume tier so that high- and low-traffic stores are balanced across treatment arms.',
    scenario: 'Store-level noise dwarfs the treatment effect; blocking by store tier shrinks the error term and reveals the lift the unblocked design missed.',
    mistakes: ['Analyzing a blocked design as if it were completely randomized, forfeiting the power gain.', 'Blocking on a variable measured after treatment, which biases the effect.'],
    sources: pool('montgomery', 'gerberGreen', 'kohavi', 'openintro', 'mixtape'),
  },
  'Factorial Designs': {
    domain: 'factorial designs',
    overview: 'Factorial designs vary multiple factors simultaneously (e.g., 2×2, 2^k), estimating main effects and — critically — interactions: whether the effect of one factor depends on the level of another; fractional factorials screen many factors economically.',
    why: 'One-factor-at-a-time testing cannot see interactions and wastes runs; factorial designs answer more questions from the same sample.',
    workplace: 'A pricing-and-promotion test crosses discount level with ad creative; the interaction term tells you whether discounts only work with the new creative.',
    scenario: 'Free shipping and a banner each show small lifts alone but a large lift together — an interaction only a factorial design could detect.',
    mistakes: ['Interpreting main effects when a strong interaction is present.', 'Confounding important effects in a fractional design by ignoring its resolution.'],
    sources: pool('montgomery', 'kohavi', 'gerberGreen', 'openintro', 'winston'),
  },
  'Multi-Armed Bandits in Online Testing': {
    domain: 'multi-armed bandits',
    overview: 'Bandit algorithms balance exploration and exploitation while a test runs: epsilon-greedy explores randomly, UCB explores optimistically by uncertainty, and Thompson sampling draws from posterior beliefs — minimizing regret instead of fixing sample sizes.',
    why: 'When opportunity cost matters (ads, headlines, promotions), bandits earn while they learn, shifting traffic toward winners long before a fixed-horizon test would end.',
    workplace: 'News and ad platforms allocate impressions with Thompson sampling, automatically retiring weak creatives.',
    scenario: 'Running four headlines as a fixed A/B/n test wastes weeks of traffic on losers; a bandit reallocates toward the winner within days.',
    mistakes: ['Using bandit traffic shares as unbiased effect estimates — adaptive allocation biases naive comparisons.', 'Deploying bandits where treatments have delayed or long-term effects the reward signal misses.'],
    sources: pool('bandits', 'sutton', 'kohavi', 'mmds', 'openintro'),
  },
  'Switchback Experiments': {
    domain: 'switchback experiments',
    overview: 'Switchback designs alternate the whole system (a market, a city) between treatment and control over time windows, addressing interference where one unit’s treatment affects another’s outcome (marketplaces, ride-sharing, pricing); analysis must respect window correlation and carryover.',
    why: 'When treatment spills across units — surge pricing changes the whole market — user-level A/B tests are biased; switchbacks restore valid inference.',
    workplace: 'Delivery platforms test dispatch algorithms by switching entire cities hourly, then aggregate window-level outcomes.',
    scenario: 'Testing courier bonuses per-courier contaminates control couriers who lose orders to treated ones; switching the whole city per hour removes the interference.',
    mistakes: ['Ignoring carryover effects between adjacent windows.', 'Analyzing window observations as independent when they are serially correlated.'],
    sources: pool('switchback', 'kohavi', 'gerberGreen', 'montgomery', 'mixtape'),
  },
  'Causal Inference': {
    domain: 'causal inference',
    overview: 'Causal inference estimates counterfactuals — what would have happened otherwise — via the potential-outcomes model: ATE/ATT/ATU, selection bias decomposition, and when experiments are impossible, quasi-experimental designs (regression discontinuity, difference-in-differences, synthetic control, instrumental variables, propensity matching, interrupted time series).',
    why: 'Most strategic questions ("did the loyalty program work?") cannot be randomized after the fact; quasi-experimental tools recover credible answers from observational data.',
    workplace: 'Policy and pricing analyses lean on diff-in-diff and synthetic control; analyst credibility rests on articulating the identifying assumptions.',
    scenario: 'A loyalty program launched only to high-value customers; naive comparison conflates selection with effect — the difference-in-means decomposition shows exactly the bias term.',
    mistakes: ['Reading the observed treated-vs-untreated gap as a causal effect (it includes selection bias).', 'Applying diff-in-diff without checking parallel pre-trends.'],
    sources: pool('mixtape', 'mhe', 'imbensRubin', 'pearl', 'gerberGreen'),
  },

  'Spark NLP & LLM': {
    domain: 'NLP at scale',
    overview: 'Modern NLP pipelines tokenize, embed, and model text at scale: Spark NLP provides distributed annotators (tokenization, NER, sentiment, embeddings), while transformer-based language models supply contextual representations consumed in those pipelines.',
    why: 'Enterprises process millions of documents; combining distributed compute with pretrained language models is how NLP ships in production.',
    workplace: 'A claims team runs Spark NLP over millions of adjuster notes, extracting entities and sentiment into warehouse tables for BI.',
    scenario: 'Regex-based extraction breaks on messy clinical notes; a pretrained NER annotator in a distributed pipeline replaces it at scale.',
    mistakes: ['Running transformer inference row-by-row instead of batched/distributed.', 'Skipping text normalization and blaming the model for noise.'],
    sources: pool('sparkNlp', 'jurafsky', 'cs224n', 'attention', 'databricks'),
  },
  'Prompt Engineering and RAG': {
    domain: 'prompting and RAG',
    overview: 'LLMs are autoregressive next-token predictors steered by prompts (instruction, context, input, output format) and sampling settings (temperature, top-p, top-k, max tokens); retrieval-augmented generation grounds them by embedding documents into a vector database and injecting retrieved context, countering temporal gaps, domain gaps, and hallucination.',
    why: 'Prompting and RAG are the two highest-leverage, lowest-cost ways to make general models useful and truthful on your organization’s data.',
    workplace: 'Teams build RAG assistants over policy documents: chunk, embed, index in a vector store, retrieve top-k chunks per question, and ground the model’s answer.',
    scenario: 'The chatbot confidently cites a refund policy that does not exist — hallucination; grounding it with retrieved policy text plus "answer only from context" fixes it.',
    mistakes: ['Blaming the model for vague output when the prompt lacked instruction, context, or format.', 'Skipping retrieval evaluation — bad chunks in means bad answers out, regardless of the model.'],
    sources: pool('ragpaper', 'anthropicDocs', 'wartonPrompt', 'langchain', 'databricks'),
  },
  'Evaluation and Deployment of GenAI': {
    domain: 'GenAI evaluation',
    overview: 'GenAI quality is measured, not assumed: golden datasets, human and LLM-as-judge scoring, groundedness/relevance/safety metrics, tracing (MLflow), guardrails, and staged deployment with monitoring close the loop from prototype to production.',
    why: 'Ungoverned GenAI fails silently and publicly; evaluation and deployment discipline is what separates demos from dependable systems.',
    workplace: 'Before launch, a RAG assistant must pass an eval suite (answer correctness, citation groundedness, refusal behavior) tracked across prompt and model versions.',
    scenario: 'A prompt "improvement" quietly degraded answer groundedness; the regression eval caught it before customers did.',
    mistakes: ['Shipping on vibes — a handful of cherry-picked demos instead of an eval set.', 'Evaluating only average quality and ignoring worst-case/safety failures.'],
    sources: pool('openaiEvals', 'mlflow', 'databricks', 'anthropicDocs', 'instructGpt'),
  },
  'Agentic AI and LLM Fine-Tuning': {
    domain: 'agents and fine-tuning',
    overview: 'Agentic systems let LLMs plan, call tools, and iterate (ReAct-style loops, function calling, multi-step workflows); fine-tuning adapts model weights to a domain — full fine-tuning, instruction tuning, RLHF, and parameter-efficient methods like LoRA that train small adapter matrices.',
    why: 'Agents extend models from answering to acting; fine-tuning and LoRA are how teams specialize models affordably when prompting and RAG are not enough.',
    workplace: 'An operations agent reads a ticket, queries the order API, drafts a response, and escalates on uncertainty — with eval-gated autonomy.',
    scenario: 'Prompted models keep misformatting legal citations; a LoRA fine-tune on 5,000 examples fixes the format at a fraction of full fine-tuning cost.',
    mistakes: ['Reaching for fine-tuning when better prompting or RAG would suffice (knowledge vs behavior confusion).', 'Granting agents tools without guardrails, evals, or human-in-the-loop checkpoints.'],
    sources: pool('reactPaper', 'lora', 'instructGpt', 'hfDocs', 'anthropicDocs'),
  },
};