// Per-class teaching contexts, part A: foundations, professional tools,
// Power BI/DAX, Python/APIs/NoSQL, and data mining.
// Keys must match the spreadsheet `Class` strings exactly (typos included);
// tool clusters are keyed `tool:<cluster-id>`.
import { pool } from './sources.mjs';

export const CONTEXTS_A = {
  'Background Vocabulary': {
    domain: 'business analytics foundations',
    overview: 'Business analytics turns raw organizational data into decisions. Its core vocabulary — observations, variables, training versus validation data, supervised versus unsupervised learning — is the grammar every later course builds on.',
    why: 'Analysts who use these terms precisely can read documentation, communicate with data scientists, and avoid silent modeling errors such as evaluating on training data.',
    workplace: 'In a typical analytics team you will scope a problem as descriptive, predictive, or prescriptive; identify the target variable and predictors; and agree on training/validation/test partitions before any model is fit.',
    scenario: 'Your manager asks you to scope a churn project: you must classify the work as descriptive, predictive, or prescriptive and name the target variable before modeling begins.',
    mistakes: ['Confusing statistical inference (understanding relationships) with machine-learning prediction (estimating unseen outcomes).', 'Reporting accuracy measured on training data, which overstates real performance.'],
    sources: pool('shmueli', 'islr', 'openintro', 'tan', 'crispdm'),
  },
  'Basics of Big Data Analytics': {
    domain: 'big data analytics',
    overview: 'Big data analytics applies the analytics toolkit to datasets whose volume, velocity, and variety exceed what a single machine handles comfortably, motivating distributed storage and compute.',
    why: 'Knowing when data is genuinely "big" — and when it is not — determines whether you reach for pandas on a laptop or a Spark cluster, a choice with large cost and complexity consequences.',
    workplace: 'Retailers analyze billions of point-of-sale transactions; the "3 Vs" framing helps you justify infrastructure choices to engineering and finance partners.',
    scenario: 'A 40 GB clickstream file will not open in Excel; you must decide whether the job needs distributed processing or just a smarter single-machine workflow.',
    mistakes: ['Assuming every large file needs a cluster — modern single machines handle tens of gigabytes.', 'Ignoring data variety (text, images, logs), which often matters more than raw volume.'],
    sources: pool('kleppmann', 'mmds', 'hadoopGuide', 'learningSpark', 'shmueli'),
  },
  'AI Overview': {
    domain: 'artificial intelligence',
    overview: 'Artificial intelligence is the broad project of building systems that perform tasks requiring human-like intelligence; machine learning is its dominant modern approach, and deep learning and generative AI are its most visible branches.',
    why: 'Distinguishing AI, ML, deep learning, and generative AI lets you evaluate vendor claims, choose appropriate techniques, and explain capabilities and limits to stakeholders.',
    workplace: 'Analysts increasingly act as translators: mapping a business request ("automate invoice triage") to the right class of AI technique and an honest feasibility estimate.',
    scenario: 'An executive asks whether the company "needs AI" for demand forecasting; you must map the request to the correct family of techniques and set realistic expectations.',
    mistakes: ['Treating AI, machine learning, and deep learning as interchangeable terms.', 'Assuming generative models are databases of facts rather than probabilistic sequence predictors.'],
    sources: pool('goodfellow', 'geron', 'cs229', 'scaling', 'shmueli'),
  },

  'tool:dev-tools': {
    domain: 'software development workflow',
    overview: 'Modern analytics work is software work: version control with Git, AI pair-programming tools such as Claude Code and Cursor, and team processes such as Agile/Scrum and Azure DevOps keep analytical code reviewable, reproducible, and shippable.',
    why: 'Analysts who use version control and AI coding tools ship faster, recover from mistakes safely, and collaborate with engineers on equal footing.',
    workplace: 'A typical flow: branch from main, develop a dbt model or Python script with an AI assistant, open a pull request, pass review and CI, and merge — all tracked in a board of sprint tasks.',
    scenario: 'You broke a production dashboard query; with Git you can diff, revert, and open a fix branch in minutes instead of reconstructing work from memory.',
    mistakes: ['Committing data files or credentials to a repository.', 'Accepting AI-generated code without reading it — the human is still accountable for correctness.'],
    sources: pool('progit', 'gitDocs', 'anthropicDocs', 'devopsDocs', 'agileManifesto'),
  },
  'tool:data-stack': {
    domain: 'modern data stack',
    overview: 'The modern data stack centers on a cloud warehouse (Snowflake), SQL-based transformation with software-engineering discipline (dbt), and warehouse-native BI tools (Sigma), often supplemented by low-code preparation tools such as Alteryx.',
    why: 'These tools define how data engineering and BI are actually practiced in 2020s companies; fluency in them is among the most requested skills in analytics job postings.',
    workplace: 'Raw data lands in Snowflake, dbt models transform it into tested, documented marts, and Sigma or Power BI serve governed self-service analytics on top.',
    scenario: 'Finance asks why two dashboards disagree; because transformations live in version-controlled dbt models, you can trace lineage from dashboard to source table.',
    mistakes: ['Building transformation logic inside BI tools where it cannot be tested or reused.', 'Ignoring warehouse compute costs — inefficient SQL directly increases the bill.'],
    sources: pool('snowflakeDocs', 'dbtDocs', 'sigmaDocs', 'alteryxDocs', 'kimball'),
  },
  'tool:excel': {
    domain: 'spreadsheet analytics',
    overview: 'Excel remains the lingua franca of business analysis: pivot tables summarize data interactively; lookup functions (VLOOKUP, XLOOKUP, INDEX/MATCH) join tables; SUMIFS aggregates conditionally; VBA and macros automate repetitive work.',
    why: 'Whatever your modeling stack, stakeholders consume and sanity-check results in Excel; deep fluency keeps you fast and credible.',
    workplace: 'Month-end close, budget variance analysis, and quick reconciliations are still pivot-table-and-SUMIFS work in most companies.',
    scenario: 'You must reconcile 12,000 invoice rows against a vendor master list before noon — a lookup plus a pivot table beats writing a script.',
    mistakes: ['Using VLOOKUP without exact-match mode (FALSE/0), silently returning wrong rows.', 'Hiding business logic in deeply nested formulas no one can audit.'],
    sources: pool('excelDocs', 'vbaDocs', 'msAccess', 'shmueli', 'knaflic'),
  },
  'tool:python-stack': {
    domain: 'scientific Python',
    overview: 'NumPy provides fast n-dimensional arrays, pandas provides labeled DataFrames for tabular work, and PyTorch/TensorFlow provide automatic differentiation and GPU compute for deep learning; MATLAB plays a similar numeric-computing role in engineering settings.',
    why: 'This stack is the default implementation language of modern data science; nearly every later concept in this course is executed with these libraries.',
    workplace: 'A churn model pipeline reads data with pandas, engineers features with NumPy operations, and trains a network in PyTorch — all inside one notebook or script.',
    scenario: 'A teammate’s loop over 10 million rows takes an hour; vectorizing it with NumPy/pandas reduces it to seconds.',
    mistakes: ['Writing Python for-loops where vectorized array operations are orders of magnitude faster.', 'Confusing pandas views and copies, producing silent SettingWithCopy bugs.'],
    sources: pool('numpyDocs', 'pandasDocs', 'pytorchDocs', 'tfDocs', 'mckinney'),
  },
  'tool:cloud': {
    domain: 'cloud platforms',
    overview: 'AWS, Microsoft Azure, and Google Cloud Platform rent elastic compute, storage, and managed data services. Analytics teams use them for warehouses, data lakes, notebooks, and model deployment without owning hardware.',
    why: 'Most enterprise data now lives in one of these clouds; knowing the shared concepts (object storage, managed databases, IAM, pay-per-use) transfers across vendors.',
    workplace: 'A typical pattern: raw files in object storage (S3/ADLS/GCS), a warehouse on top (Redshift/Synapse/BigQuery/Snowflake), and scheduled jobs or serverless functions orchestrating loads.',
    scenario: 'Your team must choose where a new data lake lives; the decision weighs existing vendor contracts, IAM integration, and egress costs more than benchmark speed.',
    mistakes: ['Leaving compute running idle — cloud cost discipline is part of the job.', 'Treating the three clouds as totally different; core concepts map almost one-to-one.'],
    sources: pool('awsDocs', 'azureDocs', 'gcpDocs', 'kleppmann', 'snowflakeDocs'),
  },
  'tool:enterprise': {
    domain: 'enterprise & supply chain systems',
    overview: 'Operational systems run the business and generate its data: POS systems capture retail transactions; ERP/procurement platforms (Ariba), vendor-management systems (Beeline), EDI platforms (SPS Commerce) exchange orders with partners; order, warehouse, and final-mile delivery systems run fulfillment; SharePoint and Access support team-level data work.',
    why: 'Analysts in systems-facing roles must understand where the data is born to interpret it correctly — every dashboard ultimately reads from these systems.',
    workplace: 'A supply-chain analyst traces a late-delivery KPI back through the final-mile system, the warehouse-management system, and the EDI order feed to find where timestamps diverge.',
    scenario: 'Sales numbers in the warehouse disagree with the POS report; you must trace the integration path to find dropped transactions.',
    mistakes: ['Treating system-of-record data as clean — operational systems optimize for transactions, not analytics.', 'Ignoring master-data mismatches (SKUs, vendor IDs) across systems.'],
    sources: pool('scm', 'edi', 'pos', 'kimball', 'msAccess'),
  },
  'tool:simulation': {
    domain: 'simulation & defense analytics',
    overview: 'Modeling, simulation & analysis (MS&A) tools — AFSIM for mission-level military simulation, NGTS for naval scenarios, Dakota for optimization and uncertainty quantification, MATLAB-adjacent environments, and domain tools such as PIANO, HAL, HJMP, and ITASE — let analysts study systems that are too expensive or dangerous to test live.',
    why: 'In defense and aerospace analytics, simulation is the primary laboratory; understanding the tool landscape lets you read studies and scope analyses credibly.',
    workplace: 'An operations analyst runs thousands of AFSIM scenario replications, then uses statistical analysis to compare system alternatives under uncertainty.',
    scenario: 'A program office asks whether a sensor upgrade is worth the cost; a designed simulation experiment in AFSIM with Dakota-driven parameter sweeps answers it without a single flight test.',
    mistakes: ['Trusting a simulation that was never validated against real-world data.', 'Running one replication per scenario and ignoring stochastic variability.'],
    sources: pool('afsim', 'dakota', 'matlabDocs', 'montgomery', 'hillier'),
  },

  'Data Modeling using Power BI': {
    domain: 'BI data modeling',
    overview: 'Power BI analyses live or die by the data model: tables imported via Power Query, related in a star schema of fact and dimension tables, with relationships whose direction and cardinality control how filters flow into every visual.',
    why: 'A correct star schema makes DAX simple and fast; a flat or snowflaked mess makes every measure a debugging session.',
    workplace: 'BI developers spend most of their modeling time shaping dimensions, configuring one-to-many relationships, and hiding fields users should not aggregate.',
    scenario: 'A report shows identical totals on every row of a category table — a classic sign of a missing or misdirected relationship you must diagnose in the model view.',
    mistakes: ['Building one giant flat table instead of facts and dimensions.', 'Enabling bidirectional filtering everywhere, creating ambiguity and performance problems.'],
    sources: pool('pbidocs', 'sqlbi', 'kimball', 'daxdocs', 'few'),
  },
  'Dax Query Language': {
    domain: 'DAX',
    overview: 'DAX (Data Analysis Expressions) is the formula language of Power BI, Power Pivot, and Analysis Services. Its heart is evaluation context: row context from iteration, filter context from the report, and CALCULATE — the only function that transforms one into the other.',
    why: 'Every non-trivial Power BI measure — year-to-date, same-period-last-year, market share, running totals — is a context manipulation; mastering context separates report builders from BI developers.',
    workplace: 'You will write measures like Total Sales, % of All Categories, and YTD Growth, debugging them by asking "what filter context is this cell evaluated in?"',
    scenario: 'Your "% of total" measure shows 100% on every row; the fix is wrapping the denominator in CALCULATE with ALL to remove the row’s own filter.',
    mistakes: ['Using a calculated column where a measure is needed (or vice versa).', 'Forgetting that a naked column reference fails without row context — aggregations or iterators are required in measures.'],
    sources: pool('sqlbi', 'daxdocs', 'pbidocs', 'kimball', 'few'),
  },
  'Data Visualization, Dashboards, & Storytelling': {
    domain: 'data visualization',
    overview: 'Visualization encodes data in position, length, and color so humans can decode it; dashboards arrange visuals for monitoring; storytelling sequences them into an argument that drives a decision.',
    why: 'Analysis only creates value when someone acts on it — chart choice, decluttering, and narrative determine whether your work changes decisions.',
    workplace: 'You will design executive dashboards (high-level KPIs, drill-downs) and analytical deep-dives, choosing bar/line/scatter encodings and stripping non-data ink.',
    scenario: 'Leadership ignores a cluttered 12-chart dashboard; rebuilding it around one key trend with annotations finally prompts the pricing decision.',
    mistakes: ['Using pie charts or dual axes where comparison accuracy matters.', 'Decorating instead of decluttering — every non-data pixel competes with the message.'],
    sources: pool('knaflic', 'few', 'munzner', 'pbidocs', 'shmueli'),
  },

  'Python Programming Language': {
    domain: 'Python',
    overview: 'Python is the default language of analytics: dynamically typed, readable, with core structures (lists, dicts, tuples, sets), control flow, functions, comprehensions, and an enormous package ecosystem.',
    why: 'Nearly every later topic — APIs, Spark, machine learning, GenAI — is practiced through Python; fluency compounds across the whole curriculum.',
    workplace: 'Day-to-day Python means reading files, cleaning data with pandas, writing functions for reuse, and gluing systems together with scripts.',
    scenario: 'You inherit a 400-line notebook with copy-pasted blocks; refactoring repeated logic into functions makes the analysis testable and reusable.',
    mistakes: ['Mutating a list while iterating over it.', 'Using mutable default arguments (def f(x, acc=[]) shares one list across calls).'],
    sources: pool('pythonDocs', 'mckinney', 'pep8', 'geron', 'pandasDocs'),
  },
  'Data Collection from Web API': {
    domain: 'web APIs',
    overview: 'Web APIs expose data over HTTP: you send a request (method, URL, headers, parameters, often a key for authentication) and parse a JSON response, respecting status codes, pagination, and rate limits.',
    why: 'APIs are how analysts acquire third-party and internal service data programmatically — stock prices, weather, CRM records — without manual exports.',
    workplace: 'A nightly job calls a vendor REST API with the requests library, handles 429 rate-limit responses with backoff, and lands JSON into the warehouse.',
    scenario: 'Your script suddenly returns 401 errors; diagnosing it means checking the expired API key in the authorization header, not your parsing code.',
    mistakes: ['Ignoring HTTP status codes and parsing error pages as data.', 'Hard-coding API keys in committed code instead of environment variables.'],
    sources: pool('requestsDocs', 'mdnHttp', 'pythonDocs', 'mckinney', 'kleppmann'),
  },
  'NoSQL Databases': {
    domain: 'NoSQL',
    overview: 'NoSQL databases trade the relational model for flexible schemas and horizontal scale: document stores (MongoDB), key-value stores, wide-column stores, and graph databases, typically embracing eventual consistency per the CAP theorem.',
    why: 'Modern applications generate semi-structured JSON-like data at scale; analysts must query it and understand why it is modeled differently than a warehouse.',
    workplace: 'Product event data often lives in MongoDB or DynamoDB; you will query documents, flatten nested fields, and decide what to replicate into the warehouse.',
    scenario: 'A product team stores orders as nested JSON documents; you must explain why analytics still wants them flattened into relational fact tables.',
    mistakes: ['Treating NoSQL as a drop-in replacement for relational databases rather than a different trade-off.', 'Ignoring eventual consistency — reads may briefly return stale data.'],
    sources: pool('mongo', 'nosqlDistilled', 'kleppmann', 'mdnHttp', 'snowflakeDocs'),
  },

  'Data Mining': {
    domain: 'data mining',
    overview: 'Data mining is the disciplined process of discovering patterns in data — framed by CRISP-DM/SEMMA-style phases: business understanding, data preparation, modeling, evaluation, deployment — spanning supervised prediction and unsupervised discovery.',
    why: 'The process matters more than any single algorithm: partitioning data, avoiding leakage, and matching technique to question is what makes results trustworthy.',
    workplace: 'A churn project walks the full cycle: define the business question, build a labeled dataset, partition train/validation/test, compare models, deploy, monitor.',
    scenario: 'A model performs brilliantly in development and fails in production; the cause is data leakage — a predictor that will not exist at prediction time.',
    mistakes: ['Skipping the business-understanding phase and modeling the wrong target.', 'Letting information from validation/test data leak into training decisions.'],
    sources: pool('shmueli', 'tan', 'crispdm', 'islr', 'sklearn'),
  },
  'Regression Review with the Data Mining Process': {
    domain: 'regression',
    overview: 'Linear regression fits a linear equation to predict a numeric target; within data mining it is re-framed for prediction: fit on training data, judge by holdout error (RMSE/MAE), not just R² and p-values.',
    why: 'Regression is the baseline every fancier model must beat, and the clearest place to learn the predictive mindset.',
    workplace: 'Price, demand, and cost models often start (and sometimes end) with multiple linear regression plus thoughtful features.',
    scenario: 'Two models have similar R² on training data, but holdout RMSE reveals one overfits — the data-mining lens picks the right winner.',
    mistakes: ['Selecting models by training R², which always improves with more predictors.', 'Interpreting coefficients causally without an experimental or quasi-experimental design.'],
    sources: pool('islr', 'shmueli', 'openintro', 'esl', 'sklearn'),
  },
  'Exploratory Data Analysis (EDA)': {
    domain: 'EDA',
    overview: 'EDA systematically inspects data before modeling: variable types and distributions, missing values and imputation, outliers, skewness and transformations, correlations, and feature engineering (binning, interactions, ratios, temporal features).',
    why: 'Most modeling failures are data failures; EDA is where you catch wrong types, leakage, missingness patterns, and the features that will actually carry signal.',
    workplace: 'Before any churn model, you will profile every variable, visualize distributions, decide an imputation strategy, and engineer features — usually 60–80% of project time.',
    scenario: 'A "numeric" zip-code column was averaging like a number; EDA catches the type error before it poisons the model.',
    mistakes: ['Dropping all rows with missing values, biasing the sample and shrinking the data.', 'Imputing using statistics computed on the full dataset, leaking test information into training.'],
    sources: pool('shmueli', 'mckinney', 'islr', 'tan', 'pandasDocs'),
  },
  'Dimension Reduction': {
    domain: 'dimension reduction',
    overview: 'Dimension reduction compresses many correlated variables into fewer informative ones — principal component analysis (PCA) projects data onto orthogonal directions of maximal variance; related ideas include variable selection and curse-of-dimensionality reasoning.',
    why: 'High-dimensional data makes models slow, unstable, and overfit-prone; reduction improves generalization and reveals latent structure.',
    workplace: 'Survey batteries and sensor feeds with dozens of correlated measures are routinely compressed with PCA before clustering or regression.',
    scenario: 'Forty correlated marketing metrics destabilize a regression; five principal components capture 90% of variance and stabilize it.',
    mistakes: ['Forgetting to standardize variables before PCA, letting large-scale variables dominate.', 'Interpreting principal components as causal factors rather than variance directions.'],
    sources: pool('islr', 'esl', 'shmueli', 'sklearn', 'tan'),
  },
  'Evaluating Model Performance': {
    domain: 'model evaluation',
    overview: 'Honest evaluation partitions data (training/validation/test or cross-validation) and scores predictions with task-appropriate metrics — RMSE/MAE/MAPE for numeric prediction — while watching for overfitting via the gap between training and holdout error.',
    why: 'Evaluation is the contract between a model and the business: it estimates how the model will behave on data it has never seen.',
    workplace: 'Model review meetings revolve around holdout metrics, error distributions, and benchmark comparisons against the naive baseline.',
    scenario: 'A forecast model must beat "predict last month" — the naive benchmark — on holdout MAPE before anyone trusts its extra complexity.',
    mistakes: ['Tuning hyperparameters against the test set, which silently turns it into training data.', 'Comparing RMSE across different target scales or transformed targets.'],
    sources: pool('shmueli', 'islr', 'esl', 'sklearn', 'tan'),
  },
  'Evaluating Model Performance - Classification Models': {
    domain: 'classification evaluation',
    overview: 'Classification evaluation starts from the confusion matrix — true/false positives and negatives — and derives accuracy, sensitivity (recall), specificity, precision, and F1, with cutoff choice trading the error types against each other.',
    why: 'With imbalanced classes (fraud, churn, disease) accuracy is misleading; choosing the right metric and cutoff is a business decision expressed statistically.',
    workplace: 'A fraud team tunes the score cutoff to hit a precision target the operations queue can handle, accepting the implied recall.',
    scenario: 'A 99%-accurate fraud model catches zero fraud because it predicts "legitimate" for everyone — the confusion matrix exposes it instantly.',
    mistakes: ['Reporting accuracy alone on imbalanced data.', 'Using the default 0.5 cutoff when error costs are asymmetric.'],
    sources: pool('shmueli', 'islr', 'sklearn', 'tan', 'esl'),
  },
  'Evaluating Model Performance - Classification and Ranking Models': {
    domain: 'ranking evaluation',
    overview: 'When models rank rather than just classify, evaluation uses the ROC curve and AUC, lift and gains charts, and decile analysis — measuring how well the model concentrates positives at the top of the ranked list.',
    why: 'Marketing, collections, and fraud teams act on the top of a ranked list; lift at the relevant depth, not global accuracy, is what drives value.',
    workplace: 'A campaign with budget for 10% of customers is judged by lift in the top decile: how many more responders than random selection.',
    scenario: 'Two models tie on AUC, but one has far better lift in the top decile — the only region the campaign will ever contact.',
    mistakes: ['Optimizing AUC when only the top decile will be actioned.', 'Reading lift charts without the random-baseline reference line.'],
    sources: pool('shmueli', 'esl', 'sklearn', 'islr', 'tan'),
  },
  'Predictive Use of Regression': {
    domain: 'predictive regression',
    overview: 'Using regression for prediction shifts attention from inference to generalization: feature selection (forward/backward/stepwise, regularization), holdout error, and parsimonious models that predict new records well.',
    why: 'A regression tuned for explanation can be bloated and fragile for prediction; the predictive framing chooses variables by validation error, not p-values.',
    workplace: 'Pricing and demand teams maintain regression models re-fit on rolling windows, selected and monitored by out-of-sample error.',
    scenario: 'Stepwise selection by AIC produces a 12-variable model, but a 5-variable version matches its holdout RMSE — parsimony wins deployment.',
    mistakes: ['Equating statistical significance with predictive usefulness.', 'Extrapolating predictions far outside the range of the training data.'],
    sources: pool('islr', 'shmueli', 'esl', 'openintro', 'sklearn'),
  },
  'Logistic Rgeression Models': {
    domain: 'logistic regression',
    overview: 'Logistic regression models the probability of a binary outcome through the logit (log-odds) link: coefficients act multiplicatively on odds, predictions are probabilities, and a cutoff converts them into classifications.',
    why: 'It is the workhorse classifier of business: interpretable, fast, well-calibrated, and the standard baseline for churn, response, default, and conversion models.',
    workplace: 'Credit and churn models report odds ratios to risk committees because "each late payment multiplies default odds by 1.8" is auditable.',
    scenario: 'Marketing wants to know which customers to call; a logistic model scores conversion probability and an ROI-based cutoff picks the call list.',
    mistakes: ['Interpreting coefficients as probability changes instead of log-odds changes.', 'Judging fit with R² instead of deviance, AUC, or calibration.'],
    sources: pool('islr', 'shmueli', 'openintro', 'esl', 'sklearn'),
  },
  'Tree-Based Models': {
    domain: 'decision trees',
    overview: 'Classification and regression trees recursively split data on the predictor and cutpoint that most purify the target (Gini, entropy, variance), forming interpretable if-then rules, controlled by pruning or complexity parameters to avoid overfitting.',
    why: 'Trees handle nonlinearity and interactions automatically, require little preprocessing, and are the building blocks of the most powerful tabular models (forests, boosting).',
    workplace: 'A single pruned tree is often presented to business owners as a set of plain-language segmentation rules they can act on.',
    scenario: 'An unpruned tree memorizes the training data with 100 leaves; cost-complexity pruning back to 9 leaves doubles holdout performance.',
    mistakes: ['Growing trees to purity without pruning — the textbook overfit.', 'Reading variable importance as causal influence.'],
    sources: pool('islr', 'shmueli', 'esl', 'tan', 'sklearn'),
  },
  'Ensembling Tree': {
    domain: 'tree ensembles',
    overview: 'Ensembles combine many trees: bagging averages trees grown on bootstrap samples; random forests add random feature subsets to decorrelate them; boosting (AdaBoost, gradient boosting, XGBoost) grows trees sequentially, each correcting the last.',
    why: 'Tree ensembles are the strongest off-the-shelf models for tabular business data, dominating churn, credit, and demand problems.',
    workplace: 'Most production tabular models in industry are random forests or gradient-boosted trees tuned on validation data.',
    scenario: 'A single tree plateaus at 0.71 AUC on churn; a tuned gradient-boosted ensemble reaches 0.79 with the same features.',
    mistakes: ['Letting boosting run too many rounds without early stopping — it will overfit.', 'Assuming ensembles need the same interpretability sacrifices everywhere; importance plots and SHAP recover much insight.'],
    sources: pool('breiman', 'esl', 'islr', 'sklearn', 'shmueli'),
  },
  'Text Mining': {
    domain: 'text mining',
    overview: 'Text mining converts unstructured text into features: tokenization, stop-word removal, stemming/lemmatization, bag-of-words and TF-IDF weighting, document-term matrices, then classification, clustering, or sentiment analysis on top.',
    why: 'Most organizational data is text — tickets, reviews, notes, contracts; mining it turns a dormant asset into predictors and insights.',
    workplace: 'Support teams route and prioritize tickets with TF-IDF + classifier pipelines; voice-of-customer teams track sentiment over product releases.',
    scenario: 'Ten thousand app reviews arrive monthly; a TF-IDF pipeline with a simple classifier surfaces the three themes driving one-star ratings.',
    mistakes: ['Skipping normalization so "Refund", "refund", and "refunds" count as different signals.', 'Treating TF-IDF scores as semantic understanding — it is still word counting.'],
    sources: pool('jurafsky', 'tan', 'shmueli', 'mmds', 'sklearn'),
  },
};