import React, { useState } from 'react';
import { useApp } from '../App';
import { clozeBack, isValidCloze } from '../../../../backend/src/core/cloze';

/**
 * AI Practice deck — the one editable deck. Generated by the tutor from weak
 * topics; cards can be edited, deleted, exported/imported, or the whole deck
 * reset. The locked course is never affected.
 */
export function Practice() {
  const { engine, toast, bump, nav } = useApp();
  const [cards, setCards] = useState(engine.store.getPracticeCards());
  const [editing, setEditing] = useState<string | null>(null);
  const [draft, setDraft] = useState('');

  const refresh = () => { setCards(engine.store.getPracticeCards()); bump(); };

  const generate = () => {
    const added = engine.generatePracticeFromWeakTopics();
    toast(added.length ? `⟐ Generated ${added.length} practice cards from weak topics` : 'No weak topics detected yet — review more first.');
    refresh();
  };

  const saveEdit = (id: string) => {
    if (!isValidCloze(draft)) { toast('Card must contain a {{c1::…}} cloze blank.'); return; }
    const all = engine.store.getPracticeCards().map((c) => (c.id === id ? { ...c, text: draft } : c));
    engine.store.setPracticeCards(all);
    engine.search.addPracticeCards(all);
    setEditing(null);
    refresh();
  };

  const exportDeck = async () => {
    const json = engine.store.exportPractice();
    try {
      await navigator.clipboard.writeText(json);
      toast('Practice deck JSON copied to clipboard.');
    } catch {
      console.log(json);
      toast('Export printed to console (clipboard unavailable).');
    }
  };

  return (
    <div>
      <h1 className="screen-title">AI Practice Deck</h1>
      <p className="screen-sub">
        Extra practice generated by the offline tutor from your weak topics. Uses the same spaced-repetition schedule,
        fully editable — and completely separate from the locked course.
      </p>
      <div style={{ display: 'flex', gap: 10, marginBottom: 16, flexWrap: 'wrap' }}>
        <button className="btn primary" onClick={generate}>⟐ Generate from weak topics</button>
        <button className="btn" onClick={() => nav({ name: 'review' })}>◈ Study (due practice cards join the queue)</button>
        <button className="btn" onClick={exportDeck}>⇪ Export JSON</button>
        <button
          className="btn danger"
          onClick={() => { if (confirm('Reset the AI Practice deck? (The locked course is unaffected.)')) { engine.store.resetPracticeDeck(); refresh(); } }}
        >
          Reset practice deck
        </button>
      </div>

      {cards.length === 0 && (
        <div className="panel" style={{ color: 'var(--fg-dim)' }}>
          No practice cards yet. Review some lessons, then generate cards from your weak topics here or from the Tutor screen.
        </div>
      )}

      {cards.map((c) => (
        <div className="panel" key={c.id} style={{ marginBottom: 10 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'baseline' }}>
            <span className="chip on">{c.topic}</span>
            <span style={{ fontSize: 11, color: 'var(--fg-dim)' }}>{new Date(c.createdAt).toLocaleDateString()}</span>
          </div>
          {editing === c.id ? (
            <div style={{ marginTop: 10 }}>
              <textarea rows={3} value={draft} onChange={(e) => setDraft(e.target.value)} />
              <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
                <button className="btn primary" onClick={() => saveEdit(c.id)}>Save</button>
                <button className="btn ghost" onClick={() => setEditing(null)}>Cancel</button>
              </div>
            </div>
          ) : (
            <>
              <p style={{ fontSize: 14.5, lineHeight: 1.6, margin: '10px 0 6px' }}>{clozeBack(c.text)}</p>
              <div style={{ display: 'flex', gap: 8 }}>
                <button className="btn ghost" onClick={() => { setEditing(c.id); setDraft(c.text); }}>Edit</button>
                <button className="btn ghost" onClick={() => { engine.store.deletePracticeCard(c.id); refresh(); }}>Delete</button>
              </div>
            </>
          )}
        </div>
      ))}
    </div>
  );
}
