from __future__ import annotations

import reflex as rx


def agent_status_panel(status, 
                       refresh_status=None, 
                       run_collection_now=None, 
                       collection_action_status="") -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.hstack(
                rx.heading("Agent Operations", 
                           size="5", 
                           color="var(--cp-text)"),
                rx.spacer(),
                rx.cond(
                    refresh_status is not None,
                    rx.button("Refresh", 
                              on_click=refresh_status, 
                              variant="soft", 
                              color_scheme="gray", 
                              size="1"),
                ),
                rx.badge(status["latest_run_status"], 
                         color_scheme="cyan"),
                width="100%",
            ),
            _row("Last database update", 
                 status["last_database_update"]),
            _row("API key", 
                 status["api_key_display"]),
            _row("API agent available", 
                 rx.cond(status["api_agent_available"], 
                         "Yes", 
                         "No")),
            _row("Latest query", 
                 status["latest_run_query"]),
            _row(
                "Latest counts",
                status["latest_run_downloaded_count"].to_string()
                + " downloaded / "
                + status["latest_run_inserted_count"].to_string()
                + " new / "
                + status["latest_run_updated_count"].to_string()
                + " updated",
            ),
            rx.cond(
                status["latest_run_diagnosis_path"] != "",
                _row("Latest diagnosis", 
                     status["latest_run_diagnosis_path"]),
            ),
            rx.cond(
                status["latest_run_reason"] != "",
                _row("Latest run reason", 
                     status["latest_run_reason"]),
            ),
            _row("Last successful run", 
                 status["last_success_time"]),
            _row("Last success records", 
                 status["last_success_records"].to_string()),
            _row("Last insufficient run", 
                 status["last_insufficient_time"]),
            _row("Last failed run", 
                 status["last_failure_time"]),
            rx.cond(
                status["last_failure_error"] != "",
                _row("Failure summary", 
                     status["last_failure_error"]),
            ),
            rx.divider(border_color="var(--c-border)"),
            _row("Desktop mode", 
                 status["desktop_mode"]),
            _row("ChemPulse API", 
                 status["active_api_base_url"]),
            _row("Backend reachable", 
                 rx.cond(status["backend_reachable"], 
                         "Yes",
                         "No")),
            _row("Database reachable", 
                 rx.cond(status["database_reachable"], 
                         "Yes", 
                         "No")),
            _row("Scaffold database", 
                 rx.cond(status["scaffold_database_loaded"], 
                         "Loaded", 
                         "Unavailable")),
            _row("Literature table", 
                 rx.cond(status["literature_table_available"], 
                         "Available", 
                         "Unavailable")),
            _row("Chemistry engine", 
                 rx.cond(status["chemistry_engine_available"], 
                         "Available", 
                         "Unavailable")),
            _row("Previous payload", 
                 rx.cond(status["previous_payload_available"], 
                         "Available", 
                         "No saved payload")),
            _row("Payload updated", 
                 status["previous_payload_updated_at"]),
            _row("Payload records", 
                 status["previous_payload_record_count"].to_string()),
            rx.cond(
                status["last_connection_error"] != "",
                _row("Connection issue", 
                     status["last_connection_error"]),
            ),
            rx.divider(border_color="var(--cp-border)"),
            _row("Collection enabled", 
                 rx.cond(status["collection_enabled"], 
                         "Yes", 
                         "No")),
            _row("Collection running", 
                 rx.cond(status["collection_running"], 
                         "Yes", 
                         "No")),
            _row("Next run", 
                 status["collection_next_run_at"]),
            _row("Last collection", 
                 status["collection_last_run_finished_at"]),
            rx.button("Run collection now",
                      on_click=run_collection_now, 
                      width="100%", 
                      variant="soft", 
                      color_scheme="cyan"),
            rx.cond(collection_action_status != "", 
                    rx.text(collection_action_status, 
                            color="var(--cp-text-muted)", 
                            size="2")),
            _row("Wired to app", 
                 rx.cond(status["agent_wired_to_app"], 
                         "Yes", 
                         "No")),
            _row("Wired to database", 
                 rx.cond(status["agent_wired_to_database"],
                         "Yes", 
                         "No")),
            align="stretch",
            spacing="2",
        ),
        class_name="bento-card",
        grid_column="span 4",
        min_height="360px",
    )


def _row(label: str, 
         value) -> rx.Component:
    return rx.hstack(
        rx.text(label, 
                color="var(--cp-text-soft)", 
                size="2"),
        rx.spacer(),
        rx.text(value, 
                color="var(--cp-text)", 
                weight="bold", 
                size="2"),
        width="100%",
        align="center",
    )


