"""Provide the canonical ChemPulse backend API handler surface."""

from backend.api.chemical_intelligence import (
    mechanism_explain,
    reaction_name_search,
    reaction_report,
    reaction_search,
    structure_search,
)
from backend.api.dashboard import (
    dashboard_data,
    dashboard_data_script,
    dashboard_diagnostics,
    documents,
    documents_script,
    galaxy_points,
    galaxy_points_script,
    journal_publications,
    journal_publications_script,
    journals,
    journals_script,
    manuscript_review,
    manuscript_review_script,
    predictive_lab_status,
    predictive_lab_status_script,
    publication_radar,
    publication_radar_script,
    publications,
    publications_script,
    research_pulse,
    research_pulse_script,
    scaffolds,
    scaffolds_script,
    top_scaffolds,
    top_scaffolds_script,
)
from backend.api.mobile import mobile_app, mobile_app_script, mobile_manifest, mobile_service_worker, mobile_summary
from backend.api.publication_routes import import_publications, literature_search
from backend.api.status import (
    desktop_status,
    desktop_status_script,
    run_collection,
    run_collection_script,
    run_health,
    topics_list,
    topics_update,
)

__all__ = [
    "dashboard_data",
    "dashboard_data_script",
    "dashboard_diagnostics",
    "desktop_status",
    "desktop_status_script",
    "documents",
    "documents_script",
    "galaxy_points",
    "galaxy_points_script",
    "import_publications",
    "journal_publications",
    "journal_publications_script",
    "journals",
    "journals_script",
    "literature_search",
    "manuscript_review",
    "manuscript_review_script",
    "mechanism_explain",
    "mobile_app",
    "mobile_app_script",
    "mobile_manifest",
    "mobile_service_worker",
    "mobile_summary",
    "predictive_lab_status",
    "predictive_lab_status_script",
    "publication_radar",
    "publication_radar_script",
    "publications",
    "publications_script",
    "reaction_name_search",
    "reaction_report",
    "reaction_search",
    "research_pulse",
    "research_pulse_script",
    "run_collection",
    "run_collection_script",
    "run_health",
    "scaffolds",
    "scaffolds_script",
    "structure_search",
    "top_scaffolds",
    "top_scaffolds_script",
    "topics_list",
    "topics_update",
]
